---
kind: pipeline
name: CentOS
steps:
  - name: run nginx build
    image: centos:latest
    commands:
#      - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
#      - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
#      - yum update -y
#      - dnf -y install sudo wget
#      - sudo wget -q -O - http://www.atomicorp.com/installers/atomic | sh
#      - dnf -y install geoip-devel perl openssl-devel gd-devel libxslt-devel zlib-devel pcre-devel rpm-build gcc make rpmdevtools rpmlint tree
#
#      - wget https://nginx.org/packages/mainline/centos/7/SRPMS/nginx-1.25.5-1.el7.ngx.src.rpm
#      - rpm -Uvh nginx-1.25.5-1.el7.ngx.src.rpm
#      - cp /drone/src/compilators/centos/nginx/phyre-nginx.spec ~/rpmbuild/SPECS/phyre-nginx.spec
#      - tree ~/rpmbuild
#      - rpmbuild -bb ~/rpmbuild/SPECS/phyre-nginx.spec
      - mkdir -p ~/rpmbuild/RPMS/x86_64
      - touch ~/rpmbuild/RPMS/x86_64/phyre-nginx-1.25.5-1.el9.x86_64.rpm

  - name: git-push
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:PhyreApps/Distributions.git
      force: false
      commit: true
      path: ~/rpmbuild/RPMS/x86_64/phyre-nginx-1.25.5-1.el9.x86_64.rpm
