---
kind: pipeline
name: CentOS
steps:
  - name: run nginx build
    image: centos:latest
    commands:
      - sudo wget -q -O - http://www.atomicorp.com/installers/atomic | sh 
      - dnf -y install geoip-devel perl openssl-devel gd-devel libxslt-devel zlib-devel pcre-devel rpm-build gcc make rpmdevtools rpmlint tree
