---
kind: pipeline
name: CentOS
steps:
  - name: run nginx build
    image: centos:latest
    environment:
      SSH_DEPLOY_KEY: ${SSH_DEPLOY_KEY}

    commands:
      - mkdir /root/.ssh && echo "$SSH_DEPLOY_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - yum update -y
#      - dnf -y install sudo wget
#      - sudo wget -q -O - http://www.atomicorp.com/installers/atomic | sh
#      - dnf -y install geoip-devel perl openssl-devel gd-devel libxslt-devel zlib-devel pcre-devel rpm-build gcc make rpmdevtools rpmlint tree
#
#      - wget https://nginx.org/packages/mainline/centos/7/SRPMS/nginx-1.25.5-1.el7.ngx.src.rpm
#      - rpm -Uvh nginx-1.25.5-1.el7.ngx.src.rpm
#      - cp /drone/src/compilators/centos/nginx/phyre-nginx.spec ~/rpmbuild/SPECS/phyre-nginx.spec
#      - tree ~/rpmbuild
#      - rpmbuild -bb ~/rpmbuild/SPECS/phyre-nginx.spec
      - dnf -y install git
      - mkdir -p /drone/src/deploy.txt
      - touch /drone/src/deploy.txt

      - touch ~/.ssh/known_hosts
      - ssh-keyscan -H github.com >> /root/.ssh/known_hosts

      - git config --global gpg.format ssh
      - git config --global user.email "drone@phyrecloud.com"
      - git config --global user.signingkey ~/.ssh/id_rsa
      - git clone git@github.com:PhyreApps/Distributions.git /drone/src/Distributions
      - cd /drone/src/Distributions
      - git checkout -b main
      - mv /drone/src/deploy.txt /drone/src/Distributions
      - git add .
      - git commit -m "Deploy to CentOS"
      - git push origin main
      - echo "Deployed to CentOS"
