---
kind: pipeline
name: CentOS
steps:
  - name: run nginx build
    image: centos:latest
    commands:
      - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - yum update -y
      - dnf -y install sudo wget
      - dnf -y install geoip-devel perl openssl-devel gd-devel libxslt-devel zlib-devel pcre-devel rpm-build gcc make rpmdevtools rpmlint tree
      - useradd builder -m
      - su - builder
      - pwd
      - cd ~
      - wget https://nginx.org/packages/mainline/centos/7/SRPMS/nginx-1.25.5-1.el7.ngx.src.rpm
      - rpm -Uvh nginx-1.25.5-1.el7.ngx.src.rpm
      - cp /compilators/centos/nginx/phyre-nginx.spec rpmbuild/SPECS/phyre-nginx.spec
      - tree ~/rpmbuild
      - rpmbuild -bb rpmbuild/SPECS/phyre-nginx.spec
