name: Compile PHYRE NGINX Package

on:
  workflow_dispatch:
    inputs:
      os_type:
        description: 'OS'
        required: true
        default: 'ubuntu-22.04'
        type: choice
        options:
          - ubuntu-22.04
          - ubuntu-20.04
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ inputs.os_type }}

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Compile NGINX
      run: |
        cd compilators/debian/nginx
        chmod 775 ./nginx-compile.sh
        ./nginx-compile.sh ${{ inputs.os_type }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: Cloud Vision Bot
        commit_user_email: bobicloudvision@gmail.com
        commit_author: Cloud Vision Bot <bobicloudvision@gmail.com>
        commit_message: Upload compiled packages [BOT]
        repository: ./compilators/debian/nginx/dist
        #skip_checkout: true
        #push_options: '--force'
        #skip_fetch: false
        #create_branch: true
        # status_options: '--untracked-files=no'
